import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Home - Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
      <main>
        {/* Banner gelecek buraya */}
        <section>
          {/*row*/}
          {/*row*/}
          {/*row*/}
          {/*row*/}
          {/*row*/}
        </section>
        {/*Modal gelecek*/}
      </main>
    </div>
  )
}

export default Home
