import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Home - Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header gelecek*/}
      Lets build movie app
      <main>
        {/* Banner gelecek buraya */}
        <section>
          {/*row*/}
          {/*row*/}
          {/*row*/}
          {/*row*/}
          {/*row*/}
        </section>
        {/*Modal gelecek*/}
      </main>
    </div>
  )
}

export default Home
